// app/todo-mvc/_header.tsx
import * as React from 'react';
import { connectTodosVM } from './todo-mvc.vm';

interface IProps {
    createTodo: (name: string) => void;
}

const HeaderDisconnected = (props: IProps) => {
    const handleBlur = (e: React.FocusEvent<HTMLInputElement>) => {
        e.currentTarget.value = '';
    }

    const handleClick = (e: React.KeyboardEvent<HTMLInputElement>) => {
        if(e.key === 'Enter') {
            const value = e.currentTarget.value;
            e.currentTarget.value = '';
            props.createTodo(value);
        }
        if(e.key === 'Escape') {
            e.currentTarget.value = '';
        }
    }

    return (
        <header className="header">
            <h1>todos</h1>
            <input 
                className="new-todo" 
                placeholder="What needs to be done?" 
                autoFocus 
                onKeyDown={handleClick} 
                onBlur={handleBlur} 
            />
        </header>
    )
}

const Header = connectTodosVM(HeaderDisconnected, vm => {
    return {
        createTodo: vm.createTodo,
    }
});

export { Header };

// app/todo-mvc/_header.svelte
<script lang="ts">
    import { connectTodosVM } from './todo-mvc.vm';

    let createTodo: (name: string) => void;

    connectTodosVM((vm) => {
        createTodo = vm.createTodo;
    })
    
    const handleBlur = (e: FocusEvent) => {
        (e.currentTarget as HTMLInputElement).value = '';
    }

    const handleClick = (e: KeyboardEvent) => {
        const target = (e.currentTarget as HTMLInputElement);

        if(e.key === 'Enter') {
            const value = target.value;
            target.value = '';
            createTodo(value);
        }
        if(e.key === 'Escape') {
            target.value = '';
        }
    }

</script>

<header class="header">
    <h1>todos</h1>
    <input 
        class="new-todo" 
        placeholder="What needs to be done?" 
        autofocus 
        on:keydown={handleClick} 
        on:blur={handleBlur} 
    />
</header>
