// app/todo-mvc/todo-mvc.svelte


<script lang="ts">
    import { withVM } from '../framework-extensions/with-vm';
    import { TodosVM } from './todo-mvc.vm';
    import { TodoStatus } from './todos.dao';
    import Header from './_header.svelte';
    import Footer from './_footer.svelte';
    import TodoList from './_todo-list/todo-list.svelte';

    export let status: TodoStatus;

    withVM(
        TodosVM, 
        () => { 
            return {
                status: status,
            };
        });

</script>

<section class="todoapp">
    <Header />
    <TodoList status={status} />
    <Footer selectedStatus={status} />
</section>

// app/todo-mvc/todo-mvc.tsx
import * as React from 'react';
import { withVM } from '../framework-extensions/with-vm';
import { TodosVM } from './todo-mvc.vm';
import { TodoStatus } from './todos.dao';
import { Footer } from './_footer';
import { Header } from './_header';
import { TodoList } from './_todo-list/todo-list';

const TodoMvcDisconnected = (props: { status: TodoStatus }) => {
    return <section className="todoapp">
        <Header />
        <TodoList status={props.status} />
        <Footer selectedStatus={props.status} />
    </section>
};

const TodoMVC = withVM(TodoMvcDisconnected, TodosVM);

export { TodoMVC }
