// app/todo-mvc/_todo-list/_todo-item.svelte
<script lang="ts">
    import { connectTodosVM } from "../todo-mvc.vm";
    import { TodoStatus } from "../todos.dao"

    export let name: string;
    export let id: number;
    export let status: TodoStatus;

    let toggleStatus: () => void;
    let removeTodo: () => void;

    connectTodosVM(vm => {
        toggleStatus = () => vm.toggleStatus(id);
        removeTodo = () => vm.removeTodo(id);
    });
</script>

<li class={status === TodoStatus.Completed ? 'completed' : ''}>
    <div class="view">
        <input class="toggle" type="checkbox" on:change={toggleStatus} checked={status === TodoStatus.Completed} />
        <label>{name}</label>
        <button class="destroy" on:click={removeTodo} />
    </div>
</li>

// app/todo-mvc/_todo-list/_todo-item.tsx
import { ITodoItem, TodoStatus } from "../todos.dao"
import * as React from 'react';
import { connectTodosVM } from "../todo-mvc.vm";

interface IContextProps {
    toggleStatus: () => void;
    removeTodo: () => void;
}

const TodoItemDisconnected = (props: IContextProps & ITodoItem) => {
    const className = props.status === TodoStatus.Completed ? 'completed' : '';
    return <li className={className}>
        <div className="view">
            <input className="toggle" type="checkbox" onChange={props.toggleStatus} checked={props.status === TodoStatus.Completed} />
            <label>{props.name}</label>
            <button className="destroy" onClick={props.removeTodo} />
        </div>
    </li>
}

const TodoItem = connectTodosVM(TodoItemDisconnected, (vm, ownProps: ITodoItem) => {
    return {
        toggleStatus: () => vm.toggleStatus(ownProps.id),
        removeTodo: () => vm.removeTodo(ownProps.id),
    }
});

export { TodoItem };
